# <center> Krystian Kierklo 162430 grupa 2</center>

# Mnożenie macierzy

In [3]:
import numpy as np

A = np.array([2, 1, 1, 1, 3, 6, 4, 5, 5]).reshape(3,3)
B = np.array([1, 0, 5, 2, 1, 6, 0, 3, 0]).reshape(3,3)

C = np.dot(A,B)

print("Mnożenie za pomocą np.dot() \n", C)

#Dokumentacja NumPy ówi jednak, że używać np.dot() należy tylko do #obliczania iloczynu skalarnego dwóch jednwymiarówych wektorów, a nie do mnożenia macierzy

D = np.matmul(A,B)
E = A@B

print("\n Mnożenie za pomocą np.matmul() \n", D)
print("\n Mnożenie za pomocą operatora @ \n", E)

Mnożenie za pomocą np.dot() 
 [[ 4  4 16]
 [ 7 21 23]
 [14 20 50]]

 Mnożenie za pomocą np.matmul() 
 [[ 4  4 16]
 [ 7 21 23]
 [14 20 50]]

 Mnożenie za pomocą operatora @ 
 [[ 4  4 16]
 [ 7 21 23]
 [14 20 50]]


# Rząd macierzy

In [4]:
import numpy as np

A = np.array([[6, 1, 1, 4],
              [4, -2, 5, 1],
              [2, 8, 7, 4],
              [2, 2, 1, 3]])

#Rank of a matrix
print("Rank od A: ", np.linalg.matrix_rank(A)) #rząd

Rank od A:  4


# Wyznacznik macierzy

### Obliczanie wyznacznika

In [6]:
import numpy as np

A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

# Determinant of a matrix
print("Determinant of A: ", np.linalg.det(A))

Determinant of A:  -306.0


# Transportowanie macierzy

In [7]:
import numpy as np

A = np.array([[4, 3, 2, 0],
              [-4, -2, -5, 1],
              [12, 8, -7, 4]])

M = np.transpose(A)
print(M)

[[ 4 -4 12]
 [ 3 -2  8]
 [ 2 -5 -7]
 [ 0  1  4]]
