# <center>Krystian Kierklo 162430 grupa 2 </center>
# <center>Zadania do wykonania </center>

### Zadanie 1
##### Posiadając poniższą macierz 2x2 napisz funkcję aby wyznaczyć do niej macierz odwrotną. Wynik porównaj z funkcją, którą posiada biblioteka NumPy.

##### a)
          [3 6]
          [0 9]
##### b)
          [-3 -9]
          [1 3]

In [47]:
import numpy as np

a = np.array([[3, 6],
              [0, 9]])

b = np.array([[-3, -9],
              [1, 3]])


def odwrotna_2x2(macierz: np.array):
    if macierz.shape != (2,2):
        raise ValueError("Podana macierz nie jest macierzą 2 na 2")
    wyznacznik = macierz[0][0] * macierz[1][1] - macierz[0][1] * macierz[1][0]
    pomocna = np.zeros((macierz.shape[0], macierz.shape[1]))
    odwrotna = np.zeros((macierz.shape[0], macierz.shape[1]))
    if wyznacznik == 0:
        raise ValueError("Wyznacznik dla tej macierzy wynosi 0 a nie może!")
    pomocna[0][0] = macierz[1][1]
    pomocna[0][1] = -macierz[1][0]
    pomocna[1][0] = -macierz[0][1]
    pomocna[1][1] = macierz[0][0]

    liczba_wierszy = pomocna.shape[0]
    liczba_kolumn = pomocna.shape[1]

    transported_matrix = np.zeros((liczba_kolumn, liczba_wierszy))
    for i in range(liczba_wierszy):
        for j in range(liczba_kolumn):
            transported_matrix[j][i] = pomocna[i][j]

    for i in range(liczba_wierszy):
        for j in range(liczba_kolumn):
            odwrotna[i][j] = transported_matrix[i][j] / wyznacznik

    return odwrotna


print("----------------------------Macierz A ------------------------------------")
print("Macierz a odwrotna według mojej funkcji: \n", odwrotna_2x2(a))
print("Macierz a odwrotna według funkcji z numpy: \n", np.linalg.inv(a))
print("----------------------------Macierz B ------------------------------------")
# print("Macierz b odwrotna według mojej funkcji: \n", odwrotna_2x2(b)) # WYZNACZIK WYNOSI 0
# print("Macierz b odwrotna według funkcji z numpy: \n", np.linalg.inv(b)) # WYZNACZIK WYNOSI 0


----------------------------Macierz A ------------------------------------
Macierz a odwrotna według mojej funkcji: 
 [[ 0.33333333 -0.22222222]
 [ 0.          0.11111111]]
Macierz a odwrotna według funkcji z numpy: 
 [[ 0.33333333 -0.22222222]
 [ 0.          0.11111111]]
----------------------------Macierz B ------------------------------------


### Zadanie

##### Posiadając poniższą macierz 3x3 napisz funkcję aby wyznaczyć do niej macierz odwrotną. Wynik porównaj z funkcją, którą posiada biblioteka NumPy.

##### a)
        [1 0 5]
        [2 7 6]
        [8 3 2]

##### b)
        [3 -1 1]
        [5 1 4]
        [-1 3 2]

In [48]:
import numpy as np

a = np.array([[1, 0, 5],
              [2, 7, 6],
              [8, 3, 2]])

d = np.array([[3, -1, 1],
              [5, 1, 4],
              [-1, 3, 2]])


def odwrotna_3x3(a: np.array):
    if a.shape[0] != a.shape[1]:
            raise ValueError("Podana macierz nie jest kwadratowa")
    elif a.shape[0] != 3 or a.shape[1] != 3:
        raise ValueError("Wprowadzona macierz nie jest macierzą 3 x 3")
    else:
        det = a[0][0]*a[1][1]*a[2][2] + a[0][1]*a[1][2]*a[2][0] + a[0][2]*a[1][0]*a[2][1] - a[0][2]*a[1][1]*a[2][0] - a[0][0] * a[1][2]*a[2][1] - a[0][1]*a[1][0]*a[2][2]

        if(det == 0):
            raise ValueError("Wyznacznik podanej macierzy jest równy 0!")

    odwrotna = np.zeros((a.shape[0], a.shape[1]))

    odwrotna[0][0] = a[1][1]*a[2][2] - a[1][2]*a[2][1]
    odwrotna[0][1] = a[0][2]*a[2][1] - a[0][1]*a[2][2]
    odwrotna[0][2] = a[0][1]*a[1][2] - a[0][2]*a[1][1]

    odwrotna[1][0] = a[1][2]*a[2][0] - a[1][0]*a[2][2]
    odwrotna[1][1] = a[0][0]*a[2][2] - a[0][2]*a[2][0]
    odwrotna[1][2] = a[0][2]*a[1][0] - a[0][0]*a[1][2]

    odwrotna[2][0] = a[1][0]*a[2][1] - a[1][1]*a[2][0]
    odwrotna[2][1] = a[0][1]*a[2][0] - a[0][0]*a[2][1]
    odwrotna[2][2] = a[0][0]*a[1][1] - a[0][1]*a[1][0]

    return odwrotna / det



print("z funkcji: \n", np.linalg.inv(a))
print("\n moja: \n", odwrotna_3x3(a))

# print("\n z funkcji: \n", np.linalg.inv(d)) WYZNACZIK WYNOSI 0
# print("\n moja: \n", odwrotna_3x3(d)) WYZNACZIK WYNOSI 0

z funkcji: 
 [[ 0.01574803 -0.05905512  0.13779528]
 [-0.17322835  0.1496063  -0.01574803]
 [ 0.19685039  0.01181102 -0.02755906]]

 moja: 
 [[ 0.01574803 -0.05905512  0.13779528]
 [-0.17322835  0.1496063  -0.01574803]
 [ 0.19685039  0.01181102 -0.02755906]]


### Zadanie 3
##### Posiadając napisane funkcję powyżej stwórz jedną funkcję, która będzie obliczała odwrotność macierzy zarówno 2x2 jak i 3x3. Sprawdź poprawność działania wykorzystując przykłady macierzy z zadań 1a,1b,2a,2b.

In [49]:
import numpy as np

a = np.array([[3, 6],
              [0, 9]])

b = np.array([[-3, -9],
              [1, 3]])

c = np.array([[1, 0, 5],
              [2, 7, 6],
              [8, 3, 2]])

d = np.array([[3, -1, 1],
              [5, 1, 4],
              [-1, 3, 2]])


def odwrotna(a: np.array):
    if a.shape == (2,2):
        wyznacznik = a[0][0] * a[1][1] - a[0][1] * a[1][0]
        pomocna = np.zeros((a.shape[0], a.shape[1]))
        odwrotna = np.zeros((a.shape[0], a.shape[1]))
        if wyznacznik == 0:
            raise ValueError("Wyznacznik dla tej macierzy wynosi 0 a nie może!")

        pomocna[0][0] = a[1][1]
        pomocna[0][1] = -a[1][0]
        pomocna[1][0] = -a[0][1]
        pomocna[1][1] = a[0][0]

        liczba_wierszy = pomocna.shape[0]
        liczba_kolumn = pomocna.shape[1]

        transported_matrix = np.zeros((liczba_kolumn, liczba_wierszy))
        for i in range(liczba_wierszy):
            for j in range(liczba_kolumn):
                transported_matrix[j][i] = pomocna[i][j]

        for i in range(liczba_wierszy):
            for j in range(liczba_kolumn):
                odwrotna[i][j] = transported_matrix[i][j] / wyznacznik

        return odwrotna

    elif a.shape == (3,3):
        if a.shape[0] != a.shape[1]:
            raise ValueError("Podana macierz nie jest kwadratowa")
        else:
            det = a[0][0]*a[1][1]*a[2][2] + a[0][1]*a[1][2]*a[2][0] + a[0][2]*a[1][0]*a[2][1] - a[0][2]*a[1][1]*a[2][0] - a[0][0] * a[1][2]*a[2][1] - a[0][1]*a[1][0]*a[2][2]
            if(det == 0):
                raise ValueError("Wyznacznik podanej macierzy jest równy 0!")

            odwrotna = np.zeros((a.shape[0], a.shape[1]))

            odwrotna[0][0] = a[1][1]*a[2][2] - a[1][2]*a[2][1]
            odwrotna[0][1] = a[0][2]*a[2][1] - a[0][1]*a[2][2]
            odwrotna[0][2] = a[0][1]*a[1][2] - a[0][2]*a[1][1]

            odwrotna[1][0] = a[1][2]*a[2][0] - a[1][0]*a[2][2]
            odwrotna[1][1] = a[0][0]*a[2][2] - a[0][2]*a[2][0]
            odwrotna[1][2] = a[0][2]*a[1][0] - a[0][0]*a[1][2]

            odwrotna[2][0] = a[1][0]*a[2][1] - a[1][1]*a[2][0]
            odwrotna[2][1] = a[0][1]*a[2][0] - a[0][0]*a[2][1]
            odwrotna[2][2] = a[0][0]*a[1][1] - a[0][1]*a[1][0]

            return odwrotna / det

    else:
        raise ValueError("Podana macierz nie jest ani macierzą 2 na 2 ani macierzą 3 na 3")





print("\n Macierz odwrotna do a według mojej funkcji: \n", odwrotna(a))
print("\n Macierz odwrotna do a według funkcji numpy: \n", np.linalg.inv(a))
print("----------------------------------------------------------------------")
# print("\n Macierz odwrotna do b według mojej funkcji: \n", odwrotna(b)) WYZNACZIK WYNOSI 0
# print("\n Macierz odwrotna do b według funkcji numpy: \n", np.linalg.inv(b)) WYZNACZIK WYNOSI 0
print("----------------------------------------------------------------------")
print("\n Macierz odwrotna do c według mojej funkcji: \n", odwrotna(c))
print("\n Macierz odwrotna do c według funkcji numpy: \n", np.linalg.inv(c))
print("----------------------------------------------------------------------")
# print("\n Macierz odwrotna do d według mojej funkcji: \n", odwrotna(d)) WYZNACZIK WYNOSI 0
# print("\n Macierz odwrotna do d według funkcji numpy: \n", np.linalg.inv(d)) WYZNACZIK WYNOSI 0
print("----------------------------------------------------------------------" )



 Macierz odwrotna do a według mojej funkcji: 
 [[ 0.33333333 -0.22222222]
 [ 0.          0.11111111]]

 Macierz odwrotna do a według funkcji numpy: 
 [[ 0.33333333 -0.22222222]
 [ 0.          0.11111111]]
----------------------------------------------------------------------
----------------------------------------------------------------------

 Macierz odwrotna do c według mojej funkcji: 
 [[ 0.01574803 -0.05905512  0.13779528]
 [-0.17322835  0.1496063  -0.01574803]
 [ 0.19685039  0.01181102 -0.02755906]]

 Macierz odwrotna do c według funkcji numpy: 
 [[ 0.01574803 -0.05905512  0.13779528]
 [-0.17322835  0.1496063  -0.01574803]
 [ 0.19685039  0.01181102 -0.02755906]]
----------------------------------------------------------------------
----------------------------------------------------------------------
