# <center> Krystian Kierklo 162430 grupa 2</center>

# 1. Wektory-wprowadzenie

### Tworzenie wektorów - python

In [1]:
import numpy as np

my_vector1 = np.array([1,2,3,4,5])
print("My vector: ", my_vector1)


My vector:  [1 2 3 4 5]


In [2]:
import numpy as np

my_vector2 = np.arange(5)
my_vector3 = np.arange(0, 10, 2)

print("My vector 2: ", my_vector2)
print("My vector 3: ", my_vector3)

My vector 2:  [0 1 2 3 4]
My vector 3:  [0 2 4 6 8]


In [3]:
import numpy as np

my_vector4 = np.linspace(1, np.pi, 4)

print("My vector 4: ", my_vector4)

My vector 4:  [1.         1.71386422 2.42772844 3.14159265]


### Operacje na wektorach

In [4]:
import numpy as np

my_vector4 = np.arange(5)
new_vector = np.append(my_vector4,[1000])

print("New vector with 1000 at the end: ", new_vector)

New vector with 1000 at the end:  [   0    1    2    3    4 1000]


In [5]:
import numpy as np

my_vector4 = np.arange(5)
new_vector_insert = np.insert(my_vector4, 1, 8888)

print("Vector with value 8888 at the index 1: ", new_vector_insert)

Vector with value 8888 at the index 1:  [   0 8888    1    2    3    4]


In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
index = 0
arr2 = np.delete(arr, index)

print("Based array: ", arr, f"Array with removed value[{index}]: ", arr2)

Based array:  [1 2 3 4 5] Array with removed value[0]:  [2 3 4 5]


### Działania na wektorach

##### Dodawanie

In [11]:
import numpy as np

vec1 = np.array([1, 2, 3, 4, 5])
vec2 = np.array([1, 2, 3, 4, 5])

adding1 = np.add(vec1, vec2)
adding2 = vec1 + vec2

print("After adding using function: ", adding1)
print("After adding without function: ", adding2)

After adding using function:  [ 2  4  6  8 10]
After adding without function:  [ 2  4  6  8 10]


##### Odejmowanie

In [15]:
import numpy as np

vec1 = np.array([1, 2, 3, 4, 5])
vec2 = np.array([5, 4, 3, 2, 1])

subtract1 = np.subtract(vec1,vec2)
subtract2 = vec1-vec2

print("After subtracting using function: ", subtract1)
print("After subtracting without function: ", subtract2)

After subtracting using function:  [-4 -2  0  2  4]
After subtracting without function:  [-4 -2  0  2  4]


##### Mnożenie przez skalar

In [16]:
import numpy as np

vec1 = np.array([1, 2, 3, 4, 5])
scalar = 3
result = vec1 * scalar

print(result)

[ 3  6  9 12 15]


##### Mnożenie i dzielenie

In [17]:
import numpy as np

vec1 = np.array([1, 2, 3, 4, 5])
vec2 = np.array([0, 2, 3, 0, 2])

multiply1 = np.multiply(vec1, vec2)
multiply2 = vec1 * vec2

print("After multipled using function: ", multiply1)
print("After multipled without function: ", multiply2)

After multipled using function:  [ 0  4  9  0 10]
After multipled without function:  [ 0  4  9  0 10]


In [34]:
import numpy as np

vec1 = np.array([1, 2, 3, 4, 15])
vec2 = np.array([1, 2, 3, 2, 5])

divide1 = np.divide(vec1, vec2)
divide2 = vec1/vec2

print("After divided using function: ", divide1)
print("After divided without function: ", divide2)

After divided using function:  [1. 1. 1. 2. 3.]
After divided without function:  [1. 1. 1. 2. 3.]


# 2. Macierze

### Macierze w python

In [19]:
import numpy as np

matrix1 = np.array([[1, 2, 3, 4, 15], [2, 4, 6, 8 ,10]])

print(matrix1)

[[ 1  2  3  4 15]
 [ 2  4  6  8 10]]


In [23]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
import numpy as np

m = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(3, 3)

X = np.matrix(m)
X

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Poruszanie się po macierzach w python

In [25]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(3,3)

first_value = x[0][0]
middle_value = x[1][1]
last_value = x[-1][-1]

print("Frist element in matri: ", first_value)
print("Middle element in matrix: ", middle_value)
print("Last element in matrix: ", last_value)

Frist element in matri:  1
Middle element in matrix:  5
Last element in matrix:  9


### Macierz diagonalna

In [26]:
import numpy as np

a = np.diag((1, 2, 3, 4))
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### Inne gotowe funkcje NumPy na tworzenie macierzy

In [27]:
import numpy as np

zeros = np.zeros((3, 3))

print(zeros)

ones = np.ones((3, 3))

print(ones)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Zmiana wartości elementów w istniejącej macierzy

In [28]:
x = zeros.copy()
x[0][2] = 6

print(x)

[[0. 0. 6.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Dodawanie i odejmowanie macierzy

In [29]:
# Dodajemy wartości odpowiednio po indeksach, które również umiemszczamy na wskazanej przez nie pozycji

# Należy pamiętać, że aby operacje dodawania lub odejmowania macierzy mogło zaistnieć musimy posiadać macierze tych samych wymiarów

# 3. Tensory

### Tensory w Python

In [ ]:
# Tensor jest identyfikowany przez trzy parametry, a mianowicie rangę, kształt i rozmiar. O liczbie wymiarów tensora mówi się, że jest jego rangą. Mówi się, że liczba kolumn i wierszy, które ma tensor, jest jego kształtem. Mówi się, że typ danych przypisny do elementów tensora jest jego typem

### Tworzenie tensorów w Python

In [ ]:
# Tensory w Python można tworzyć na kilk sposobów. Jednym z nim jest użycie biblioteki NumPy (np.array()), innym rozwiązaniem jest wykorzystanie biblioteki TensorFlow.

### Tensorflow

In [33]:
# using the constant() function
import tensorflow as tf

t1 = tf.constant([1, 2, 3])
t2 = tf.constant([[1.1, 2.2, 3.3], [4, 5, 6]])
t3 = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
t4 = tf.constant(["String_one", "String_two", "String_three"])

print(t1, "\n")
print(t2, "\n")
print(t3, "\n")
print(t4)



tf.Tensor([1 2 3], shape=(3,), dtype=int32) 

tf.Tensor(
[[1.1 2.2 3.3]
 [4.  5.  6. ]], shape=(2, 3), dtype=float32) 

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32) 

tf.Tensor([b'String_one' b'String_two' b'String_three'], shape=(3,), dtype=string)
